//  Created by B.T. Franklin on 1/5/20.

class ArpeggioInstruments {
    
    static let shared = ArpeggioInstruments()
    
    let instrumentNames: [String]
    
    private init() {
        self.instrumentNames = [
// ON PROBATION for acting weird
//            "Stereo Grand",
//            "Bright Grand",
//            "Electric Grand",
//            "Honky-Tonk",
            "Tine Electric Piano",
            "Chorused Tine EP",
            "FM Electric Piano",
            "Chorused FM EP",
            "Harpsichord",
            "Coupled Harpsichord",
            "Clavinet",
            "Celeste",
            "Glockenspiel",
            "Music Box",
            "Vibraphone",
            "Marimba",
            "Xylophone",
            "Tubular Bells",
            "Church Bells",
            "Dulcimer",
            "Tonewheel Organ",
            "Detuned Tnwl. Organ",
            "Percussive Organ",
            "Detuned Perc. Organ",
            "Rock Organ",
            "Pipe Organ",
            "Pipe Organ 2",
            "Reed Organ",
            "Accordian",
            "Harmonica",
            "Bandoneon",
            "Nylon Guitar",
            "Steel Guitar",
            "Jazz Guitar",
            "Clean Guitar",
            "Overdrive Guitar",
            "Distortion Guitar",
            "Acoustic Bass",
            "Finger Bass",
            "Pick Bass",
            "Fretless Bass",
            "Slap Bass 1",
// DISABLED because it doesn't seem to sound right when arpeggiating
//          "Slap Bass 2",
            "Synth Bass 1",
            "Synth Bass 101",
            "Synth Bass 2",
            "Violin",
            "Viola",
            "Cello",
            "Stereo Strings Trem",
// DISABLED because the stereo version is fine
//          "Mono Strings Trem",
            "Pizzicato Strings",
            "Orchestral Harp",
            "Voice Oohs",
            "Synth Voice",
            "Trumpet",
            "Trumpet 2",
            "Trombone",
            "Trombone 2",
            "Tuba",
            "Muted Trumpet",
            "Muted Trumpet 2",
            "French Horns",
            "Solo French Horn",
            "Brass Section",
// DISABLED because the stereo version is fine
//          "Brass Section Mono",
            "Synth Brass 1",
            "Soprano Sax",
            "Alto Sax",
            "Tenor Sax",
            "Baritone Sax",
            "Oboe",
            "English Horn",
            "Bassoon",
            "Clarinet",
            "Piccolo",
            "Flute",
            "Recorder",
            "Pan Flute",
            "Bottle Blow",
            "Shakuhachi",
            "Irish Tin Whistle",
            "Ocarina",
            "Square Lead",
            "Square Wave",
            "Saw Lead",
            "Saw Wave",
            "Synth Calliope",
            "Chiffer Lead",
            "Charang",
            "Solo Vox",
            "Bass & Lead",
            "Polysynth",
            "Ice Rain",
            "Crystal",
            "Synth Mallet",
            "Atmosphere",
            "Brightness",
// ON PROBATION for acting weird
//            "Star Theme",
            "Sitar",
            "Banjo",
            "Shamisen",
            "Koto",
            "Kalimba",
            "Fiddle",
            "Shenai",
            "Tinker Bell",
            "Steel Drums",
        ]
    }
    
}
