//  Created by B.T. Franklin on 4/20/20.

class LeadInstruments {
    
    static let shared = LeadInstruments()
    
    let instrumentNames: [String]
    
    private init() {
        self.instrumentNames = [
            "Electric Grand",
            "Tine Electric Piano",
            "Chorused Tine EP",
            "FM Electric Piano",
            "Chorused FM EP",
            "Harpsichord",
            "Coupled Harpsichord",
            "Clavinet",
            "Celeste",
            "Music Box",
            "Vibraphone",
            "Dulcimer",
            "Tonewheel Organ",
            "Detuned Tnwl. Organ",
            "Percussive Organ",
            "Detuned Perc. Organ",
            "Rock Organ",
            "Pipe Organ",
            "Pipe Organ 2",
            "Reed Organ",
            "Muted Guitar",
            "Overdrive Guitar",
            "Distortion Guitar",
            "Steel Drums",
            "Violin",
            "Viola",
            "Cello",
            "Double Bass",
            "Pizzicato Strings",
            "Orchestral Harp",
            "Stereo Strings Fast",
            "Voice Oohs",
            "Synth Voice",
            "Trombone",
            "Trombone 2",
            "Tuba",
            "French Horns",
            "Solo French Horn",
            "Alto Sax",
            "Tenor Sax",
            "Baritone Sax",
            "English Horn",
            "Bassoon",
            "Piccolo",
            "Flute",
            "Recorder",
            "Irish Tin Whistle",
            "Ocarina",
            "Saw Wave",
            "Synth Calliope",
            "Chiffer Lead",
            "Solo Vox",
            "Bass & Lead",
            "Fantasia",
            "Polysynth",
            "Space Voice",
            "Halo Pad",
            "Ice Rain",
            "Synth Mallet",
            "Atmosphere",
            "Brightness",
            "Star Theme",
            "Sitar",
            "Banjo",
            "Shamisen",
            "Koto",
            "Kalimba",
            "Fiddle",
            
            "Marimba",
            "Xylophone",
            "Tubular Bells",
            "Church Bells",
            "Accordian",
            "Bandoneon",
            "Nylon Guitar",
            "Steel Guitar",
            "Jazz Guitar",
            "Clean Guitar",
            "Agogo",
            "Synth Strings 1",
            "Synth Strings 2",
            "Trumpet",
            "Trumpet 2",
            "Muted Trumpet",
            "Muted Trumpet 2",
            "Synth Brass 1",
            "Synth Brass 2",
            "Soprano Sax",
            "Oboe",
            "Clarinet",
            "Pan Flute",
            "Bottle Blow",
            "Shakuhachi",
            "Square Lead",
            "Square Wave",
            "Saw Lead",
            "Charang",
            "5th Saw Wave",
            "Crystal",
            "Tinker Bell",
        ]
    }
    
}
