//  Created by B.T. Franklin on 3/1/20.

class AccompanimentInstruments {
    
    static let shared = AccompanimentInstruments()
    
    let instrumentNames: [String]
    
    private init() {
        self.instrumentNames = [
            "Electric Grand",
            "Tine Electric Piano",
            "Chorused Tine EP",
            "FM Electric Piano",
            "Chorused FM EP",
            "Harpsichord",
            "Coupled Harpsichord",
            "Clavinet",
            "Celeste",
            "Music Box",
            "Vibraphone",
            "Dulcimer",
            "Tonewheel Organ",
            "Detuned Tnwl. Organ",
            "Percussive Organ",
            "Detuned Perc. Organ",
            "Rock Organ",
            "Pipe Organ",
            "Pipe Organ 2",
            "Reed Organ",
            "Muted Guitar",
            "Overdrive Guitar",
            "Distortion Guitar",
            "Steel Drums",
            "Violin",
            "Viola",
            "Cello",
            "Double Bass",
            "Pizzicato Strings",
            "Orchestral Harp",
            "Stereo Strings Fast",
            "Voice Oohs",
            "Synth Voice",
            "Trombone",
            "Trombone 2",
            "Tuba",
            "French Horns",
            "Solo French Horn",
            "Alto Sax",
            "Tenor Sax",
            "Baritone Sax",
            "English Horn",
            "Bassoon",
            "Piccolo",
            "Flute",
            "Recorder",
            "Irish Tin Whistle",
            "Ocarina",
            "Saw Wave",
            "Synth Calliope",
            "Chiffer Lead",
            "Solo Vox",
            "Bass & Lead",
            "Fantasia",
            "Polysynth",
            "Space Voice",
            "Halo Pad",
            "Ice Rain",
            "Synth Mallet",
            "Atmosphere",
            "Brightness",
            "Star Theme",
            "Sitar",
            "Banjo",
            "Shamisen",
            "Koto",
            "Kalimba",
            "Fiddle",
            "Shenai",
        ]

    }
    
}
